/*v1*************************************************************************************/
/* This is developed at Carnegie Mellon University in collaboration with Autel Robotics */
/*                                                                                      */
/* PI:                                                                                  */
/* George Kantor                                                                        */
/*                                                                                      */
/* Authors:                                                                             */ 
/* Weizhao Shao                                                                         */
/* Cong Li                                                                              */
/* Srinivasan Vijayarangan                                                              */
/*                                                                                      */
/* Please refer to the contract document for details on license/copyright information.  */
/****************************************************************************************/
#include <visual_frontend/reprojection_fns.h>

#include <math.h>

namespace reprojectionFns {
  double DepthExp1(double T1, double T2, double T3, 
			  double tx, double ty, double tz, 
			  double xbk1i, double ybk1i, 
			  double xk1i, double yk1i, double zk1i, 
			  double xbki, double ybki) {

    return T1-T3*xbki+xk1i*(xbki*(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+((ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)-zk1i*(xbki*(((tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)-ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))-yk1i*(xbki*(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz));
  }

  double DepthExp2(double T1, double T2, double T3, 
			  double tx, double ty, double tz, 
			  double xbk1i, double ybk1i, 
			  double xk1i, double yk1i, double zk1i, 
			  double xbki, double ybki) {
    return T2-T3*ybki+yk1i*(-ybki*(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+((tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)-zk1i*(ybki*(((tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+xk1i*(ybki*(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz));
  }
  
  double NoDepthExp1(double T1, double T2, double T3, 
			    double tx, double ty, double tz, 
			    double xbk1i, double ybk1i, 
			    double xbki, double ybki) {
    return xbk1i*((T2-T3*ybki)*(((ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)+(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))*(T2*xbki-T1*ybki)-(tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))*(T1-T3*xbki))-ybk1i*((T1-T3*xbki)*(((tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)+(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))*(T2*xbki-T1*ybki)+(tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))*(T2-T3*ybki))-(T2*xbki-T1*ybki)*(((tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)+(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))*(T1-T3*xbki)+(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))*(T2-T3*ybki);
  }

  std::vector<double> DepthExp1Jacobian(double T1, double T2, double T3, 
			   double tx, double ty, double tz, 
			   double xbk1i, double ybk1i, 
			   double xk1i, double yk1i, double zk1i, 
			   double xbki, double ybki) {
    std::vector<double> depth_exp1_Jacobian;
    depth_exp1_Jacobian.push_back(1.0);
    depth_exp1_Jacobian.push_back(0);
    depth_exp1_Jacobian.push_back(-xbki);
    depth_exp1_Jacobian.push_back(-xk1i*(xbki*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+tx*(ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(ty*ty+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+zk1i*(xbki*((tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+tx*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-yk1i*(xbki*(sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((tx*tx)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(tx*tx)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-(tx*tx)*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-(tx*tx)*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));

    depth_exp1_Jacobian.push_back(-yk1i*(xbki*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-tx*(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-tx*(ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-xk1i*(xbki*(-sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-((ty*ty)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*2.0)/(tx*tx+ty*ty+tz*tz)+ty*(ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(ty*ty+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+zk1i*(xbki*((ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+ty*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((ty*ty)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));

    depth_exp1_Jacobian.push_back(zk1i*(xbki*(tz*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-xk1i*(xbki*(-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*2.0)/(tx*tx+ty*ty+tz*tz)+tz*(ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(ty*ty+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-yk1i*(xbki*(-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((tz*tz)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));
  
    return depth_exp1_Jacobian;
  }

  std::vector<double> DepthExp2Jacobian(double T1, double T2, double T3, 
			   double tx, double ty, double tz, 
			   double xbk1i, double ybk1i, 
			   double xk1i, double yk1i, double zk1i, 
			   double xbki, double ybki) {
    std::vector<double> depth_exp2_Jacobian;
    
    depth_exp2_Jacobian.push_back(0);
    depth_exp2_Jacobian.push_back(1.0);
    depth_exp2_Jacobian.push_back(-ybki);
    depth_exp2_Jacobian.push_back(-xk1i*(ybki*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-(tx*tx)*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-(tx*tx)*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-yk1i*(ybki*(sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((tx*tx)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(tx*tx)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*2.0)/(tx*tx+ty*ty+tz*tz)+tx*(tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+zk1i*(ybki*((tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+tx*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-((tx*tx)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+(tx*tx)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));
  
    depth_exp2_Jacobian.push_back(-yk1i*(ybki*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+ty*(tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+zk1i*(ybki*((ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+ty*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-xk1i*(ybki*(-sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-((ty*ty)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-tx*(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)-tx*(ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));

    depth_exp2_Jacobian.push_back(zk1i*(ybki*(tz*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-yk1i*(ybki*(-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*2.0)/(tx*tx+ty*ty+tz*tz)+tz*(tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+xk1i*(-ybki*(-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((tz*tz)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));
  
    return depth_exp2_Jacobian;
  }

  std::vector<double> NoDepthExp1Jacobian(double T1, double T2, double T3, 
			   double tx, double ty, double tz, 
			   double xbk1i, double ybk1i, 
			   double xbki, double ybki) {
    std::vector<double> nodepth_exp1_Jacobian;

    nodepth_exp1_Jacobian.push_back(-ybk1i*(-ybki*(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+((tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)+ybki*(((tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)-xbk1i*(ybki*(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz));

    nodepth_exp1_Jacobian.push_back(xbk1i*(xbki*(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+((ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)-xbki*(((tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)-ybk1i*(xbki*(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz));

    nodepth_exp1_Jacobian.push_back(-xbki*(tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))-ybki*(ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+xbk1i*(xbki*(tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))-ybki*(((ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0))+ybk1i*(ybki*(tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+(tx*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz))+xbki*(((tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+1.0)));

    nodepth_exp1_Jacobian.push_back((T2*xbki-T1*ybki)*((tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+tx*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-xbk1i*((T2*xbki-T1*ybki)*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T1-T3*xbki)*(-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(tx*(ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(ty*ty+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))*(T2-T3*ybki))+(T2-T3*ybki)*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+ybk1i*((T2-T3*ybki)*(-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(tx*tx)*ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T1-T3*xbki)*((tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+tx*(tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tx*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))-(T2*xbki-T1*ybki)*(sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((tx*tx)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(tx*tx)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0))-(T1-T3*xbki)*(-sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-((tx*tx)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+(tx*tx)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));

    nodepth_exp1_Jacobian.push_back((T2*xbki-T1*ybki)*((ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+ty*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+ybk1i*(-(T2*xbki-T1*ybki)*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T2-T3*ybki)*(-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(ty*(tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))*(T1-T3*xbki))-(T1-T3*xbki)*(-(tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*ty*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+(ty*ty)*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-xbk1i*((T1-T3*xbki)*(-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T2*xbki-T1*ybki)*(-sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-((ty*ty)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T2-T3*ybki)*((ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+ty*(ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+ty*sin(sqrt(tx*tx+ty*ty+tz*tz))*(ty*ty+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)))+(T2-T3*ybki)*(sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((ty*ty)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(ty*ty)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0));

    nodepth_exp1_Jacobian.push_back((tz*(tx*tx+ty*ty)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+ty*ty)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))*(T2*xbki-T1*ybki)-(T1-T3*xbki)*(-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T2-T3*ybki)*(-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)-xbk1i*((T2*xbki-T1*ybki)*(-(tx*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)-(ty*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T2-T3*ybki)*((tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+tz*(ty*ty+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(ty*ty+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+(T1-T3*xbki)*(sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)+((tz*tz)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0))+ybk1i*(-(T2*xbki-T1*ybki)*(-(ty*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0))/(tx*tx+ty*ty+tz*tz)+(tx*tz*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)-tx*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+ty*(tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)+(T1-T3*xbki)*((tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*-2.0)/(tx*tx+ty*ty+tz*tz)+tz*(tx*tx+tz*tz)*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0+tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*(tx*tx+tz*tz)*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0))+(T2-T3*ybki)*(-sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/sqrt(tx*tx+ty*ty+tz*tz)-((tz*tz)*cos(sqrt(tx*tx+ty*ty+tz*tz)))/(tx*tx+ty*ty+tz*tz)+(tz*tz)*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*sin(sqrt(tx*tx+ty*ty+tz*tz))*1.0/pow(tx*tx+ty*ty+tz*tz,3.0/2.0)+tx*ty*tz*(cos(sqrt(tx*tx+ty*ty+tz*tz))-1.0)*1.0/pow(tx*tx+ty*ty+tz*tz,2.0)*2.0)));
  
    return nodepth_exp1_Jacobian;
  }

}
